# Generated by Django 5.2.3 on 2025-06-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_Scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageembedding',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='face_Scan.uploadedimage'),
        ),
        migrations.AddIndex(
            model_name='imageembedding',
            index=models.Index(fields=['image'], name='face_Scan_i_image_i_d09b22_idx'),
        ),
    ]
